from .grupo import Grupo
from .grado import Grado
from .departamento import Departamento
from .autoridad import Autoridad
from .cargo import Cargo
from .categoria_cargo import CategoriaCargo
from .tipo_dedicacion import TipoDedicacion
from .facultad import Facultad
from .universidad import Universidad
from .orientacion import Orientacion
from. materia import Materia
